### ISSUE TITLE
The S3 option deleteRemoved is not documented in the readme

### ISSUE THREAD

**Issue by tylerzey** [k1LoW/serverless-s3-sync#52]
Hi there!

I was having an issue with this plugin removing js files from a create-react-app deploy. 

Users would have these files cached and they would then 404 on after a deploy because serverless-s3-sync defaults to deleteRemoved: true.

https://github.com/k1LoW/serverless-s3-sync/blob/master/index.js#L80

Are you open to a PR that outlines this option in the readme? It took me some source diving to discover that it was possible not to delete removed files.

I'm more than happy to write the documentation.

Thanks!

**Comment by k1LoW** [comment]
Hi @tylerzey !  Thank you for your report !!!

> Are you open to a PR that outlines this option in the readme?

Yes !!
