### ISSUE TITLE
S3 sync fails if provider.region is a variable

### ISSUE THREAD

**Issue by rachetfoot** [k1LoW/serverless-s3-sync#70]
This means we have to duplicate variables in a mono-repo because the references to shared variables break s3-sync. It appears that s3-sync does not attempt to resolve the variable at all.

**Comment by williamsandonz** [comment]
This is also affecting me, basically provider.region: ${env:foo} is not resolved and the sync fails.
I've created PR [here](https://github.com/k1LoW/serverless-s3-sync/pull/72): Could we please get have this reviewed and merged?

**Comment by clay-spfmlp** [comment]
It looks like `provider.getCredentials().region` always returns undefined no matter what you have region set to. We are trying to deploy to aws gov cloud and it breaks the whole deployment. If we replace `provider.getCredentials().region` with `provider.getRegion()`, it works.
