### ISSUE TITLE
AWS provider.region not set

### ISSUE THREAD

**Issue by redstone78** [k1LoW/serverless-s3-sync#78]
in index.js on line 77 we are not setting the region, we need to update it like this below so that we can get the region:

```
   } else {
      //in this else condition, region is never set, so setting it and assigning to correct region issue
      region = provider.getRegion()
      awsCredentials = provider.getCredentials().credentials
    }
```

**Comment by kking124** [comment]
it should probably be something like:

```
region = provider.getRegion() || provider.getCredentials().region;
```

this would allow the config to supersede any default region in the credentials. Thoughts?

**Comment by redstone78** [comment]
> it should probably be something like:
> 
> ```
> region = provider.getRegion() || provider.getCredentials().region;
> ```
> 
> this would allow the config to supersede any default region in the credentials. Thoughts?

Yeah that should work.

**Comment by kking124** [comment]
see https://github.com/k1LoW/serverless-s3-sync/pull/80
